# -*- coding: utf-8 -*-
"""a00565542_4.2_computeStatistics.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUx3kMUM2sbBVK25fhQ1z1jWxn3djssJ
"""

"""Materia: Pruebas de software y aseguramiento de la calidad.

Tarea: 4.2 Ejercicio de programación 3 - Count Words.

Autor: Héctor Raúl Vázquez González - A00565542.
"""
import sys
import time


def read_file():
    """Read a file."""
    with open("P3/" + FILE_NAME, mode='r', encoding='utf-8') as file:
        data = file.readlines()
        file.close()
        return data

def write_document(data):
    """Create a file."""
    with open("P3/" + WRITE_FILE, mode='a', encoding='utf-8') as file:
        file.write(data)
        file.close()
        return true