# -*- coding: utf-8 -*-
"""a00565542_4.2_computeStatistics.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUx3kMUM2sbBVK25fhQ1z1jWxn3djssJ
"""

"""Materia: Pruebas de software y aseguramiento de la calidad.

Tarea: 4.2 Ejercicio de programación 3 - Count Words.

Autor: Héctor Raúl Vázquez González - A00565542.
"""
import sys
import time

# Reading file name from parameters
FILE_NAME = sys.argv[1]
WRITE_FILE = "StatisticsResults.txt"

def calcular_estadisticas(archivo_entrada, archivo_salida):
    try:
        with open(archivo_entrada, 'r') as file:
            # Lee la lista de números desde el archivo y convierte a una lista de floats
            lista_numeros = [float(line.strip()) for line in file.readlines()]

            # Calcula las estadísticas sin usar librerías externas
            n = len(lista_numeros)
            mean = sum(lista_numeros) / n

            # Calcula la mediana
            lista_numeros.sort()
            if n % 2 == 0:
                median = (lista_numeros[n // 2 - 1] + lista_numeros[n // 2]) / 2
            else:
                median = lista_numeros[n // 2]

            # Calcula la moda
            conteo = {}
            for numero in lista_numeros:
                conteo[numero] = conteo.get(numero, 0) + 1
            moda = max(conteo, key=conteo.get)

            # Calcula la desviación estándar y la varianza
            suma_cuadrados = sum((x - mean) ** 2 for x in lista_numeros)
            stdev = (suma_cuadrados / n)**0.5
            variance = suma_cuadrados / n

            # Guarda los resultados en un archivo de salida
            with open(archivo_salida, 'w') as output_file:
                output_file.write(f'Media: {mean}\n')
                output_file.write(f'Mediana: {median}\n')
                output_file.write(f'Moda: {moda}\n')
                output_file.write(f'Desviación Estándar: {stdev}\n')
                output_file.write(f'Varianza: {variance}\n')

            print(f'Las estadísticas se han guardado en el archivo: {archivo_salida}')

    except FileNotFoundError:
        print(f'Error: El archivo "{archivo_entrada}" no se encuentra.')
    except ValueError:
        print('Error: El archivo debe contener solo números.')

def main():
    """Principal function to count words"""
    calcular_estadisticas(FILE_NAME, WRITE_FILE)
print(main())
